name: Pengupil Testing
on:
  push:
    branches:
      - main
jobs:
  test:
    name: Functional Test
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
        - name : Checkout the Repo
          uses: actions/checkout@v4

        - name: Create isolated network
          run: docker network create --driver bridge isolated

        - name: Deploy AUT
          run: docker build -t quiz-pengupil .

        - name: Run AUT
          run: docker run --network=isolated -p 80:80 --name docker-apache -t -d quiz-pengupil:latest

        - name: Get AUT URL
          run: |
            URL=http://$(ip -f inet -o addr show docker0 | awk '{print $4}' | cut -d '/' -f 1)
            echo "URL=$URL" >> $GITHUB_ENV

        - name: Check AUT URL
          run: curl ${{ env.URL }}

        - name: Selenium Preparation
          run: docker run --network=isolated -d -p 4444:4444 -p 7900:7900 -v /dev/shm:/dev/shm --name firefox-standalone selenium/standalone-firefox:latest

        - name: db setup
          run: docker run --network=isolated --name quiz-db -e MYSQL_ROOT_PASSWORD=password -e MYSQL_DATABASE=quiz_pengupil -v ${{ github.workspace }}/db:/docker-entrypoint-initdb.d -d mysql:5.7

        - name: db wait
          run: sleep 30

        - name: db exec
          run: docker exec quiz-db sh -c 'mysql -h localhost -uroot -ppassword quiz_pengupil < /docker-entrypoint-initdb.d/quiz_pengupil.sql'
          
        - name: wait for selenium hub
          run: sh wait.sh
        
        - name: check hub
          run: curl http://localhost:4444/ui

        - name: ls debug "/var/www/html"
          run: docker exec docker-apache ls /var/www/html

        - name: ls debug "/"
          run: docker exec docker-apache ls /


        - name: install selenium
          run: pip install selenium
        
        - name: run test register
          run: python registerTest.py ${{ env.URL }}
          continue-on-error: true

        - name: run test login
          run: python loginTest.py ${{ env.URL }}        
          continue-on-error: true

        - name: 'upload artifacts'
          uses: actions/upload-artifact@v4
          with:
            name: Screenshot
            path: screenshot.png

        - name: stop docker
          run: docker stop docker-apache