name: UAS Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-chrome
        ports:
          - 4444:4444

      mysql:
        image: mysql:5.7
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: quiz_pengupil
          MYSQL_USER: user
          MYSQL_PASSWORD: password

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      run: |
        docker build -t quiz-pengupil .

    - name: Run Docker container
      run: |
        docker run --network=isolated -d -p 80:80 --name quiz-pengupil quiz-pengupil
        sleep 30

    - name: Install dependencies
      run: |
        pip install selenium

    - name: Run Register Tests
      run: |
        python registerTest.py

    - name: Run Login Tests
      run: |
        python loginTest.py

    - name: Stop and remove Docker container
      run: |
        docker stop quiz-pengupil
        docker rm quiz-pengupil