name: UAS Tests

on: [push, pull_request]

jobs:
  test:
    name: UAS Test
    runs-on: ubuntu-latest
    permissions: write-all

    services:
      mysql:
        image: mysql:5.7
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: quiz_pengupil
          MYSQL_USER: user
          MYSQL_PASSWORD: password

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    - name: Create isolated network
      run: docker network create --driver bridge isolated

    - name: Selenium Preparation
      run: docker run --network=isolated -d -p 4444:4444 -p 7900:7900 -v /dev/shm:/dev/shm --name firefox-standalone selenium/standalone-firefox:latest

    - name: Build Docker image
      run: |
        docker build -t quiz-pengupil .

    - name: Run Docker container
      run: |
        docker run -d -p 80:80 --name quiz-pengupil quiz-pengupil
        sleep 30

    - name: Install dependencies
      run: |
        pip install selenium

    - name: Run Register Tests
      run: |
        python registerTest.py

    - name: Run Login Tests
      run: |
        python loginTest.py

    - name: Stop and remove Docker container
      run: |
        docker stop quiz-pengupil
        docker rm quiz-pengupil